version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis_db
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 2s
      retries: 5
    restart: always
  clip_cutter:
    image: ghcr.io/raimannma/clip-cutter
    build: .
    command: -c 29676241 -r "ACE stev0rr#OTTO" -r "Erika Mustermann#ACEND" --remove-matches --vod-ids 2019605698
    env_file: .env
    volumes:
      - ./matches:/app/matches
      - ./clips:/app/clips
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis:
