services:
  clip_cutter:
    image: ghcr.io/raimannma/clip-cutter
    build: .
    env_file: .env
    volumes:
      - ./matches:/app/matches
      - ./clips:/app/clips
      - ./twitch-dl:/usr/local/bin/twitch-dl
      - ./model.onnx:/app/model.onnx
      - ./state/processed:/processed
      - ./state/failed:/failed
    labels:
      "com.centurylinklabs.watchtower.enable": "false"
