version: '3.8'

services:
  clip_cutter:
    image: ghcr.io/raimannma/clip-cutter
    build: .
    env_file: .env
    volumes:
      - ./matches:/app/matches
      - ./clips:/app/clips
      - ./twitch-dl:/usr/local/bin/twitch-dl
      - ./model.onnx:/app/model.onnx
      - ./processed:/processed
    labels:
      "com.centurylinklabs.watchtower.enable": "false"
