version: '3.8'

services:
  clip_cutter:
    image: ghcr.io/raimannma/clip-cutter
    build: .
    env_file: .env
    volumes:
      - ./matches:/app/matches
      - ./clips:/app/clips
      - ./twitch-dl:/usr/local/bin/twitch-dl
      - ./model.onnx:/app/model.onnx
      - ./processed:/processed
    labels:
      "com.centurylinklabs.watchtower.enable": "false"
  web:
    image: ghcr.io/raimannma/clip-cutter
    build: .
    env_file: .env
    command: "gunicorn -w 4 -b 0.0.0.0:8000 api:app"
    expose:
      - 8000
    ports:
      - "8000:8000"
    environment:
      VIRTUAL_HOST: clip-viewer.manuel-hexe.de
      VIRTUAL_PORT: 8000
      BASE_DIR: /clips/
    volumes:
      - ./clips-public:/clips/
      - ./api.py:/app/api.py
      - ./index.html:/app/index.html
      - ./favicon.ico:/app/favicon.ico
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
